name: Check Spelling
on:
  pull_request:
    paths:
    - .github/workflows/check_spelling.yml
    - '**.html'

jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.2
      - uses: actions/cache@v2
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod
      - run: go install github.com/client9/misspell/cmd/misspell@v0.3.4
      - run: misspell -error -source text content/**/*.html
